# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09bdda67547dc5bc435b81879bfb79016944025cd13710b08326600ca4d6bc1f3d7f6ee3a112fc39b65df52271243882c8be41c145f1bfad2445954391fde2f9

test:
  secret_key_base: 23da7976cb85aa7cfb3691f758e1cc674d4ab171b26247a53969e399831839e9796ec5f3f00d68a7d2e552733df2a58eccbc19ecb7e55b907b69f1e97f082e26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
